apiVersion: v1
kind: Service
metadata:
  name: deepspeed-new-svc
spec:
  selector:
    app: deepspeed-new
  clusterIP: None
  ports:
  - name: ssh
    port: 22
---
apiVersion: apps/v1
kind: StatefulSet 
metadata:
  labels:
    app: deepspeed-new 
  name: deepspeed-new
spec:
  podManagementPolicy: "Parallel"
  serviceName: deepspeed-new-svc
  replicas: 1 
  selector:
    matchLabels:
      app: deepspeed-new
  template:
    metadata:
      labels:
        app: deepspeed-new
    spec:
      containers:
      - image: us-docker.pkg.dev/flius-vpc-2/flius-vpc-2-repo/deepspeed:v5
        name: deepspeed-new
        command: ["/bin/sh", "-c", "/tmp/start.sh"]
        imagePullPolicy: Always
        volumeMounts:
        - name: hostfile 
          mountPath: "/config"
          readOnly: true
        resources:
          limits:
            nvidia.com/gpu: 1 
      nodeSelector:
        cloud.google.com/gke-nodepool: gpu-pool
      volumes:
      - name: hostfile 
        configMap:
          name: hostfile-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hostfile-config 
data:
  hostfile: |
    deepspeed-new-0.deepspeed-new-svc slots=1 
    deepspeed-new-1.deepspeed-new-svc slots=1
    deepspeed-new-2.deepspeed-new-svc slots=1 
